#!/usr/bin/env python3
"""
Turn the printed manual (DEFUSAL.docx) into structured JSON.

Nothing in the digital manual is retyped: it is built from this extraction, so
the two cannot drift in wording. Emits manual/rules.js as a plain global, NOT JSON: the digital manual has to
open from file:// on a phone or a memory stick, and fetch() of a local JSON
file is blocked there by the same-origin rules. A <script> tag is not.
"""
import json, os, re, sys, zipfile
from xml.etree import ElementTree as ET

W = '{http://schemas.openxmlformats.org/wordprocessingml/2006/main}'
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DOCX = sys.argv[1] if len(sys.argv) > 1 else os.path.join(os.path.dirname(ROOT), 'DEFUSAL.docx')
OUT  = os.path.join(ROOT, 'manual', 'rules.js')

def text_of(node):
    return ''.join(t.text or '' for t in node.iter(W + 't'))

def runs_of(p):
    """(text, bold) pairs, so emphasis in the print survives into the web page."""
    out = []
    for r in p.iter(W + 'r'):
        t = ''.join(x.text or '' for x in r.iter(W + 't'))
        if not t:
            continue
        rpr = r.find(W + 'rPr')
        bold = rpr is not None and rpr.find(W + 'b') is not None
        if out and out[-1][1] == bold:
            out[-1][0] += t
        else:
            out.append([t, bold])
    return [[t, b] for t, b in out]

def style_of(p):
    ppr = p.find(W + 'pPr')
    if ppr is None:
        return ''
    st = ppr.find(W + 'pStyle')
    return st.get(W + 'val') if st is not None else ''

def is_list(p):
    ppr = p.find(W + 'pPr')
    return ppr is not None and ppr.find(W + 'numPr') is not None

def table_of(tbl):
    rows = []
    for tr in tbl.findall(W + 'tr'):
        rows.append([text_of(tc).strip() for tc in tr.findall(W + 'tc')])
    return rows

def main():
    z = zipfile.ZipFile(DOCX)
    root = ET.fromstring(z.read('word/document.xml'))
    body = root.find(W + 'body')

    blocks = []
    for child in body:
        if child.tag == W + 'p':
            txt = text_of(child).strip()
            if not txt:
                continue
            blocks.append({'kind': 'list' if is_list(child) else 'p',
                           'style': style_of(child),
                           'text': txt,
                           'runs': runs_of(child)})
        elif child.tag == W + 'tbl':
            rows = table_of(child)
            if any(any(c for c in r) for r in rows):
                blocks.append({'kind': 'table', 'rows': rows})

    # split into modules on the "Module Difficulty: X" marker
    doc_title = blocks[0]['text'] if blocks else 'THE MANUAL'
    modules, cur = [], None
    for i, b in enumerate(blocks):
        m = re.match(r'^Module Difficulty:\s*(\w+)$', b.get('text', ''))
        if m:
            cur = {'difficulty': m.group(1).lower(), 'name': None,
                   'tagline': None, 'blocks': []}
            modules.append(cur)
            continue
        if cur is None:
            continue
        if cur['name'] is None and b['kind'] == 'p':
            cur['name'] = b['text']; continue
        if cur['tagline'] is None and b['kind'] == 'p':
            cur['tagline'] = b['text']; continue
        cur['blocks'].append(b)

    # the module id the code knows it by
    IDS = {
        'Triangles': 'triangles', 'Venn Diagram': 'venn',
        'Rationality': 'rationality', 'Angles': 'angles',
        'Sequences': 'sequences', 'Unit Conversions': 'units',
        'Parallel Lines Cut by a Transversal': 'parallel',
        'Mutually Exclusive Events': 'mutex',
    }
    missing = [m['name'] for m in modules if m['name'] not in IDS]
    if missing:
        sys.exit('unmapped module heading(s): %r' % missing)
    for m in modules:
        m['id'] = IDS[m['name']]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    data = {'title': doc_title, 'modules': modules}
    with open(OUT, 'w', encoding='utf8') as f:
        f.write('/* GENERATED by tools/extract-manual.py from the printed\n'
                '   manual. Do not edit: edit the .docx and run the tool. */\n')
        f.write('var MANUAL_RULES = ')
        json.dump(data, f, ensure_ascii=False, indent=1)
        f.write(';\n')

    print('%d modules -> %s' % (len(modules), os.path.relpath(OUT, ROOT)))
    for m in modules:
        tables = sum(1 for b in m['blocks'] if b['kind'] == 'table')
        print('  %-12s %-6s %2d blocks, %d table(s)'
              % (m['id'], m['difficulty'], len(m['blocks']), tables))

main()
